### PR TITLE
ADD required config to RTCPeerConnection test

### PR DESCRIPTION
**Pull request by ggarber**
**Description**

**Purpose**

### CODE REVIEW

**Review by fippo — COMMENTED** [review]
why? Don't tell me chromes unprefixed RTCPeerConnection requires an argument here?

**Comment by ggarber** [comment]
Chrome 55:

```
> new webkitRTCPeerConnection()
VM145:1 Uncaught TypeError: Failed to construct 'RTCPeerConnection': 1 argument required, but only 0 present.
    at <anonymous>:1:1
(anonymous) @ VM145:1
> new webkitRTCPeerConnection(null)
RTCPeerConnection { …}
```

**Comment by fippo** [comment]
Right, that is the old behaviour of webkitRTCPeerConnection. But adapter is hiding that error, no?

**Comment by ggarber** [comment]
You are right, it was a problem in my code not supporting the constructor without arguments.   But in rest of adapter tests you always use RTCPeerConnection(null), so maybe you want to homogenize it at some point.

Feel free to close it.   Thx

**Pull request closed without merging**
