### PR TITLE
improved ice server filter

### PR DESCRIPTION
**Pull request by fippo**
**Description**
improved ice server filter. Should make apprtc work but if you could test it before merging that would be great.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
LGTM

**Comment by Tinet-AaronAn** [comment]
Thanks fippo for the reply, so i can not use stun? must use turn for Edge?

**Comment by Tinet-AaronAn** [comment]
Micosoft msdn said that they support stun.

https://msdn.microsoft.com/zh-cn/library/mt502501(v=vs.85).aspx

**Comment by fippo** [comment]
yet this still does not work and results in an InvalidAccessError:

```
var g = new RTCIceGatherer({iceServers:[{urls: "stun:stun.l.google.com:19302?transport=udp"}]})
```

**Comment by Tinet-AaronAn** [comment]
hi fippo, I got this work on new RTCPeerConnection, but it dont get the correct public ip addr.
iceOptions.gatherPolicy= 'all';
iceOptions.iceServers = {urls: "stun:stun.l.google.com:19302"}; //not array but just object.

**Comment by fippo** [comment]
STUN is not supported so if you just supply a STUN server no ice servers will be used and you don't get a public ip. No way around this, use a TURN server.

**Comment by Tinet-AaronAn** [comment]
Thanks a lot, I have gave up run webRTC on Edge.
By the way, I use sipjs (sipjs.com) and it works on chrome very well.

**Pull request merged**
