### PR TITLE
reset blob url on track addition

### PR DESCRIPTION
**Pull request by fippo**
one thing I originally wanted in #182
basically that is required to show video in a scenario like audio->audio/video

Do we want a test for this? I think I can use https://github.com/webrtc/testrtc/blob/master/src/js/camresolutionstest.js#L353-L361 to assert video is shown but that would need an update of the utils first.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Do we have to do revoke URL on the old streams as well?

**Comment by KaptenJansson** [comment]
WRT to the tests, they are always welcome however that can be done in a separate PR due to need to add things to utils.

**Comment by KaptenJansson** [comment]
What's needed for revoking? Just keep track of the old stream and revoke it before/after a new track is added?

**Comment by fippo** [comment]
we don't currently revoke so this doesn't change the behaviour. Maybe we should revoke?

**Comment by fippo** [comment]
revoked. @KaptenJansson ^^

**Comment by KaptenJansson** [comment]
Awesome ;). LGTM

**Pull request merged**
