### PR TITLE
Edge lowercase algo

### PR DESCRIPTION
**Pull request by davies147**
Edge requires Dtls fingerprint 'algorithm' parameter to be lower case

Fixes an instance of the c004e001 error. When using Asterisk generated SDP, the line:
  a=fingerprint:SHA-256 ...
is RFC valid, but results in an algorithm of 'SHA-256'; Edge requires 'sha-256'

### CODE REVIEW

**Comment by davies147** [comment]
Oops, apologies for the many unwanted commits - all except the last one are no-ops because I branched from the wrong place.

**Comment by davies147** [comment]
Not entirely sure why Travis failed that...

**Comment by fippo** [comment]
I think i'd rather have this in sdp.js -- should be a 1-line change in https://github.com/fippo/sdp/blob/master/sdp.js#L239

**Comment by davies147** [comment]
@fippo - I agree in terms of clean code, and that is initially how I fixed it, but "fixing" something that is not broken just because Edge is stupid? That burns :( 

OTOH... Will you update https://github.com/fippo/sdp/blob/master/sdp.js#L239 or should I submit a pull request?

**Comment by fippo** [comment]
@davies147 I saw an opportunity to increase test coverage -- https://github.com/fippo/sdp/pull/7 :-)

**Comment by davies147** [comment]
Closing this PR because the change has been made in https://github.com/fippo/sdp/blob/master/sdp.js#L239 as discussed above.

**Pull request closed without merging**
