### PR TITLE
test: add test for fiddling with localDescription

### LINKED ISSUE #651: chrome: add test for fiddling with the .localDescription
I hereby pledge to write the test for the .localDescription accessor that @henbos wanted in https://github.com/webrtc/adapter/pull/637#discussion_r135084687

### PR DESCRIPTION
**Pull request by fippo**
as promised fixes #651

### CODE REVIEW

**Comment by fippo** [comment]
needs to be rebased ontop of #726

**Comment by fippo** [comment]
@henbos can you please take a look?

**Review by henbos — APPROVED** [review]
LGTM

**Comment by fippo** [comment]
was already rebased btw ;-)

**Review by KaptenJansson — APPROVED** [review]

**Pull request merged**
