### PR TITLE
test: add safari webdriver support

### PR DESCRIPTION
**Pull request by fippo**
tests are still not running but this adds more infrastructure to make them run

### CODE REVIEW

**Comment by fippo** [comment]
@youennf any preferences on "TechPreview" vs "TechnologyPreview"?

**Comment by youennf** [comment]
Either is good, TechnologyPreview might be slightly more consistent

**Comment by fippo** [comment]
I squeezed it in :-)

**Comment by KaptenJansson** [comment]
LGTM

**Pull request merged**
