### PR TITLE
Refreshing release adapter.js

### PR DESCRIPTION
**Pull request by youennf**
Updated  release adapter.js according trunk

### CODE REVIEW

**Comment by fippo** [comment]
@KaptenJansson @MirkoBonadei : i'd like to get some more stuff into the next release, in particular #507, #522, #523, #524 and #530

But yes, we should have a new release

**Comment by KaptenJansson** [comment]
adapter under releases/ is generated from src/ and is provided for bower. It should not be updated manually, it's done part of the npm publish step. Sorry for being slow publishing a new release.

**Comment by youennf** [comment]
Is it ok to publish a new release now?

**Comment by fippo** [comment]
https://www.npmjs.com/package/webrtc-adapter 3.4.1 was published 10 hours ago :-)

**Comment by youennf** [comment]
Great, thanks!

**Pull request closed without merging**
