### PR TITLE
chrome: bump native chrome addTrack to 63+

### PR DESCRIPTION
**Pull request by fippo**
lets postpone using the native one a bit further, there still seems to be something broken with DTMF (but behind flag)

@henbos PTAL

### CODE REVIEW

**Review by henbos — APPROVED** [review]
LGTM

**Comment by fippo** [comment]
tests seem flaky, locally it passes

**Comment by fippo** [comment]
@henbos I'm a bit concerned that we still get failures with experimental platform features flag on. I can reproduce with this build locally. Maybe something interferes now?

We might decide to update the expectation, I doubt 62 is fix-able now.

**Comment by fippo** [comment]
the second failure is caused by `'ontrack' in RTCPeerConnection.prototype and us not overriding that. That looks like something we might have to either override or extend the shim to polyfill .transceiver even in native ontrack

**Comment by henbos** [comment]
I believe ["track event / is called by setRemoteDescription during renegotiation"](https://github.com/webrtc/adapter/blob/7160e47653b9cd6394f0835b524ef5c4d779cc00/test/e2e/ontrack.js#L98) fails because the shim relies on streams being added events ([which only fires for new streams](https://crbug.com/768131)), and when track2 is added stream1 already exists. I believe this should always fail and we should update the expected files.

What's the shim status of transceiver (not supported yet)?

What's the flaky bit? From what I can tell we do things based on promises resolving, no race, and they should either succeed or fail every time. If something is flaky maybe we're doing something wrong with shim promises?

**Comment by fippo** [comment]
we do shim .transceiver in crude (but effective) ways: https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L54

**Comment by fippo** [comment]
added a commit to update one test expectation. jsfiddle for the renegotiation one:
https://jsfiddle.net/p1kueu86/
Still happens in chrome-unstable for me, you might want to take a look.

**Pull request merged**
