### PR TITLE
firefox: shim offerToReceive*: false

### PR DESCRIPTION
**Pull request by fippo**
which changed behaviour with RTCRtpTransceivers

### CODE REVIEW

**Comment by KaptenJansson** [comment]
@jan-ivar could you PTAL?

**Comment by jan-ivar** [comment]
I'd rather fix this on Firefox, in https://bugzilla.mozilla.org/show_bug.cgi?id=1425618

**Comment by fippo** [comment]
SGTM. Ltes keep this open until you land. It will also be interesting to see if anyone complains even though I doubt people test properly in Nightly

**Comment by fippo** [comment]
actually closing it is easier ;-)

**Pull request closed without merging**
