### PR TITLE
Adding onaddstream shim

### PR DESCRIPTION
**Pull request by youennf**
**Description**
Adding onaddstream shim based on ontrack

**Purpose**
ontrack is defined in WebRTC spec, onaddstream is not

### CODE REVIEW

**Comment by KaptenJansson** [comment]
@youennf Thanks for the contribution. Could you please sign the CLA? Will take a look after then, thanks!

**Comment by KaptenJansson** [comment]
Ping

**Comment by youennf** [comment]
Should be good to review I think.

**Comment by fippo** [comment]
can you rebase and force-push please? That should make travis happy

**Review by KaptenJansson — APPROVED** [review]
LGTM

**Comment by KaptenJansson** [comment]
Ow was a bit fast there, it would be great if you do a followup PR with a test covering this shim.

**Pull request merged**
