### PR TITLE
Fix Chrome dtmf shim to work with native sender.

### PR DESCRIPTION
**Pull request by jan-ivar**
**Description**
Should fix https://github.com/webrtc/adapter/issues/552.

**Purpose**
Keep spec dtmf working.

### CODE REVIEW

**Comment by fippo** [comment]
LGTM. But we also need to make addTrack work again, i'll take a look

**Review by aiham — CHANGES_REQUESTED** [review]
Since #548 has been merged, could we prefix the globals with `window.` in this PR?

**Comment by KaptenJansson** [comment]
LGTM after the window prefixes has been added.

**Comment by jan-ivar** [comment]
Done.

**Comment by fippo** [comment]
the dtmf test seems a bit flaky?

**Comment by KaptenJansson** [comment]
Kicking tests to see if they want to play along today.

**Pull request merged**
