### PR TITLE
test: remove selenium tests

### PR DESCRIPTION
**Pull request by fippo**
removes the selenium tests which have largely been superseeded by the karma ones.

I don't see much value in the remaining tests and they are currently the biggest issue getting things to go green (mainly because of https://bugzilla.mozilla.org/show_bug.cgi?id=1332122)

Still need to update test/README.md.

selenium will stay with us for the samples at least ;-)

### CODE REVIEW

**Review by KaptenJansson — APPROVED** [review]

**Comment by fippo** [comment]
@jan-ivar do you see much value in the tests that were removed?

**Comment by jan-ivar** [comment]
@fippo Lgtm. I suppose one area where "impossible constraints" still mean the same on all browsers would be `{width: {min: 9999}}`, but I guess by unit-testing constraints conversion with before/after tests, we site-step relying on browser behavior which tends to be hard to test in these environments.

**Comment by KaptenJansson** [comment]
I'm thinking it's probably good to update the README in this PR as well, WDYT?

**Review by KaptenJansson — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
