### PR TITLE
re-enable firefox tests with geckodriver

### PR DESCRIPTION
**Pull request by fippo**
**Purpose**

this re-enables tests in Firefox 47+ using geckodriver

### CODE REVIEW

**Comment by fippo** [comment]
tests look broken -- they should wait for loadedmetadata. Will try to fix that as well.

**Comment by fippo** [comment]
hrm. Tests fail in ESR (45) now which doesn't support geckodriver. What the...

**Comment by fippo** [comment]
@jan-ivar @KaptenJansson wdyt? i'd rather have tests in current firefox and not in ESR than the other way round

**Comment by KaptenJansson** [comment]
There is now way to run gecko for current and the old for ESR? I guess it's hard to figure out if its ESR from within the code. 

Your reasoning is fine by me.

**Comment by fippo** [comment]
I tried and failed. Its either me or the new selenium stuff not working on the old ESR...

**Comment by fippo** [comment]
also removed Edge since the VM I spun up is down again.

**Comment by KaptenJansson** [comment]
LGTM. Nice refactoring of the tests too!

**Comment by fippo** [comment]
LOADED_DATA is courtesy of @pehrsons ;-)

(errr.. HAVE_ENOUGH_DATA)

**Comment by Pehrsons** [comment]
Hmm, you mean readyState 4? That's HAVE_ENOUGH_DATA.

If you could make it get triggered by the "canplaythrough" event instead of using a timeout though, that would be even better.

**Pull request merged**
