### PR TITLE
Chrome unstable: addTrack works with DTMF, update expectations

### PR DESCRIPTION
**Pull request by henbos**
Chrome has now been fixed, expectations updated accordingly on unstable. See #733

### CODE REVIEW

**Comment by henbos** [comment]
PTAL @KaptenJansson

**Review by fippo — APPROVED** [review]
firefox needs a kick in the... somewhere :-)

**Comment by zaxy78** [comment]
@fippo does this PR has anything to do with the failing test on master?
```
 inserts DTMF
      ✔ when using addStream
      ✖ when using addTrack
````

**Comment by fippo** [comment]
@zaxy78 no that test has been particularly flaky. Needs a kick or two from someone with commit bit then its usually fine

**Review by KaptenJansson — APPROVED** [review]

**Pull request merged**
