### PR TITLE
add generateCertificate, fixes #41

### LINKED ISSUE #41: Need to support static methods on RTCPeerConnection
In implementing generateCertificate, which is a static method on RTCPeerConnection, we discovered that defining RTCPeerConnection as a function (and doing no more) hid the static method in Chrome (if the RTCPeerConnection class declaration was made visible).

Is it enough / correct to add "RTCPeerConnection.prototype = webkitRTCPeerConnection.prototype" to get static functions to work, or do we need to do something more complex?
We don't have any static functions so far, so I have nothing to test on.

Asking @fippo @jan-ivar for advice.

### PR DESCRIPTION
**Pull request by fippo**
@KaptenJansson @alvestrand
Not sure if I want to do the same for FF... maybe we should just drop support for versions < 38? Trivial to add though. cc @jan-ivar

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Nice work! ;)

Maybe we should look over all version checks? Not sure what versions we have committed to support, be aware of Firefox ESR though which lags behind for a while, I think it's still 38.

Also having a test for this would be nice, otherwise LGTM.

**Comment by alvestrand** [comment]
That was quick :-)
Travis' hiccups seem to be a problem with fetching external content.
Should we add a function that throws a "notSupported" error when the function is not present?

**Comment by fippo** [comment]
@alvestrand code that wants to use it will have to check if that is a function anyway (if anyone is using it at all)

**Comment by KaptenJansson** [comment]
Filed #159 WRT to checking versions just to make sure we do not forget.

**Comment by fippo** [comment]
Is this only available in M49 when setting --enable-experimental-web-platform-features?
Should we do that for beta and canary? I don't want it to be an assumption we make for stable.

**Comment by KaptenJansson** [comment]
LGTM

**Pull request merged**
