### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by MirkoBonadei**
**Description**

**Purpose**

### CODE REVIEW

**Comment by MirkoBonadei** [comment]
@fippo Is this what you need?

I am pulling into also some changes on sdp.js. PTAL and let me know.

**Comment by fippo** [comment]
Yes. Now I suspect you don't have the necessary npm rights to do the actual publish... :-/

**Comment by MirkoBonadei** [comment]
Let me try..

**Comment by MirkoBonadei** [comment]
Ok, I can't publish on npm. I am trying to recover them.

**Comment by fippo** [comment]
pinging @bemasc here too ;-)

**Comment by MirkoBonadei** [comment]
@fippo Thanks to @bemasc we have published 3.3.3.

**Comment by fippo** [comment]
hrm. There seems to be a step missing to update https://github.com/webrtc/adapter/releases
But the immediate problem is solved so not an urgent issue

**Comment by MirkoBonadei** [comment]
I can fix that. Do you have a meaningful title for the release?

**Comment by fippo** [comment]
"Edge bugfix release" is the only thing i can think of. Thanks!

**Comment by MirkoBonadei** [comment]
Done, thanks!

**Pull request merged**
