### PR TITLE
Fixing 'Cannot read property 'length' of undefined'

### PR DESCRIPTION
**Pull request by llKoull**
**Description**
PR to fix the issue "Cannot read property 'length' of undefined" https://github.com/webrtcHacks/adapter/issues/1020

### CODE REVIEW

**Review by OlivierJM — CHANGES_REQUESTED** [review]
You need to change the `!=` to `!==` otherwise eslint won't let that pass and also since the value to check is `null` it should still work fine.

**Comment by OlivierJM** [comment]
@fippo bringing this to your attention, we are also having a similar issue with the adapter.

**Comment by llKoull** [comment]
Ok, i did the change for eslint verification ;)

**Review by OlivierJM — APPROVED** [review]
Thanks for making the changes, I hope this gets merged soon.

**Comment by fippo** [comment]
I would still like to understand *why* the errors happens -- in particular when checking for null helps when it should at most be undefined.

**Comment by ksocha** [comment]
@fippo After changing `!=` to `!==` as @OlivierJM requested this solution would not work.

**Comment by fippo** [comment]
overtaken by #1066

**Pull request closed without merging**
