### PR TITLE
fix adapter-latest.js typo

### PR DESCRIPTION
**Pull request by ngauthier**
**Description**

Fixes typo in adapter-latest.js symlink (extra s from 68a18a6aabef42b53da540ddfb384cbcf56928aa )

**Purpose**

Fix the link in the readme so that it correctly points to the latest version.

:heart: @ngauthier

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Sorry about this again.....So much for doing things like this at 6pm just before going home....

**Comment by KaptenJansson** [comment]
And Thanks for fixing!

**Comment by KaptenJansson** [comment]
And I will make this a more automatic process so that the human errors like this do not happen again.

**Comment by ngauthier** [comment]
NP! Thanks for the quick merge.

**Comment by KaptenJansson** [comment]
semi-automatic publish fix is in #239. Yes there are that many steps required.....Will consider making it more portable and pretty in the future but it will do for now.

**Pull request merged**
