### PR TITLE
Edge: update localdescription and remotedescription with ice candidates

### PR DESCRIPTION
**Pull request by fippo**
**Description**
this updates the local/remote description when ice candidates are emitted

**Purpose**
enabling non-trickle ice is the main use-case

**version considerations**
Not urgent, but should be a minor version. Together with #217

### CODE REVIEW

**Comment by KaptenJansson** [comment]
LGTM

**Comment by KaptenJansson** [comment]
This needs a rebase now ;).

**Comment by fippo** [comment]
rebased -- but I think I want to update the m and c lines before merging.

**Comment by fippo** [comment]
more code than i wanted to write for that so unless someone specifically requests it...

**Comment by KaptenJansson** [comment]
OK, merging. Do you want file an issues explaining the change you intended to do?

**Comment by fippo** [comment]
did in my fork which i use to track edge-specific issues

**Comment by KaptenJansson** [comment]
Good stuff!

**Pull request merged**
