### PR TITLE
Remove RTCPeerConnection shims in FF44+

### PR DESCRIPTION
**Pull request by jan-ivar**
This avoids the "moz prefix" deprecation warnings with adapter.js in Firefox 44 (releasing Tuesday).

### CODE REVIEW

**Comment by jan-ivar** [comment]
Related to https://github.com/webrtc/adapter/issues/151, though checking on mozGetUserMedia should still be valid for a good while.

**Comment by fippo** [comment]
\o/
the diff looks confusing, the actual code is much better

**Comment by jan-ivar** [comment]
Yes, I had to change indentation for quite a few lines. Here's the [same diff ignoring whitespace](https://github.com/webrtc/adapter/pull/168/files?w=1).

**Comment by KaptenJansson** [comment]
LGTM (yes, changing whitespaces really screws up the diff ;))

**Comment by jan-ivar** [comment]
@KaptenJansson  Can we push a new version of https://webrtc.github.io/adapter/adapter-latest.js ? Not sure how that's done. It's not been updated yet, so I get deprecation warnings with adapter in Firefox now.

**Comment by KaptenJansson** [comment]
will do, sorry for missing it yet again.

**Comment by KaptenJansson** [comment]
done!

**Comment by jan-ivar** [comment]
Thanks! works now.

**Pull request merged**
