### PR TITLE
Bump version 6.1.5

### PR DESCRIPTION
**Pull request by KaptenJansson**
**Description**

**Purpose**

### CODE REVIEW

**Review by fippo — APPROVED** [review]
i wonder why the bundle shrunk so much...

**Review by fippo — CHANGES_REQUESTED** [review]
bundle doesn't seem to include sdp?

**Comment by KaptenJansson** [comment]
hmm

**Comment by fippo** [comment]
@alvestrand so who ended up with the short straw? :-)

**Comment by fippo** [comment]
the big difference in lines is because SDP is now just included once. This was changed by accident in https://github.com/webrtc/adapter/commit/9c720d155b720ac369ef75cc3a21ae8258713c2c

**Review by fippo — APPROVED** [review]

**Pull request merged**
