### PR TITLE
common: dont override createDataChannel if it does not exist

### LINKED ISSUE #799: createDataChannel() call fails on Edge 41
- [x] I have provided steps to reproduce (e.g. a link to a [jsfiddle](https://jsfiddle.net/))
- [x] I have provided browser name, version and adapter.js version
- [x] This issue only happens when adapter.js is used

## Versions affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Edge 41.xx

**adapter.js (e.g. 6.1.0)**
6.1.4

## Description
When using `adapter.js` with Edge, `createDataChannel()` exists but crashes when used. 

## Steps to reproduce
- Go to [https://jsfiddle.net/8g6k4cqu/2/](https://jsfiddle.net/8g6k4cqu/2/)
- Run
- Check console

## Expected results
[`RTCDataChannel` not found.](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/rtcdatachannels/?filter=f3f0000bf&search=rtc&q=data%20channels)

## Actual results
```
SCRIPT5007: Unable to get property 'apply' of undefined or null reference
```

### PR DESCRIPTION
**Pull request by fippo**
fixes #799 

cc @lgrahl

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Still red, haven't looked into the failures.

**Review by KaptenJansson — APPROVED** [review]
Code LGTM.

**Comment by fippo** [comment]
its just flakyness I assume. kicking the tests often enough.. ;-)

**Comment by KaptenJansson** [comment]
Test failures unrelated, 3 tries and still red.

**Pull request merged**
