### PR TITLE
Use eslint

### LINKED ISSUE #176: Move from JSHint and JSCS to ESLint
As per samples.

### PR DESCRIPTION
**Pull request by KaptenJansson**
**Description**
Eslint is a lot faster than jshint and friends. Also we had only enabled linting on some files. This time it's the other way around, all files in src/ and test/ will be checked.

Fixes #176 

**Purpose**
Improve linting

### CODE REVIEW

**Comment by fippo** [comment]
changed my git user.email to something that is covered by an individual CLA to make googlebot happier...

**Comment by KaptenJansson** [comment]
Might need a commit though

**Comment by KaptenJansson** [comment]
@samdutton PTAL and let me know if anything is out of whack.

**Comment by KaptenJansson** [comment]
@samdutton merging this now due to lots of other PR's are pending and I would like to get this in before. Please let me know in a comment here, in a new issue or PR if something is wrong. Thanks!

**Pull request merged**
