### PR TITLE
augment RTCIceCandidate constructor

### PR DESCRIPTION
**Pull request by fippo**
basically #527 but
* does not call onicecandidate too often
* implements the functionality 'natively' in the Edge shim

### CODE REVIEW

**Comment by fippo** [comment]
oops, missing tests :-/

**Comment by KaptenJansson** [comment]
LGTM when a test is added :)

**Comment by fippo** [comment]
note: for-next-major-version

**Comment by fippo** [comment]
dont-merge-just-yet

needs some more work since the spec now says the component is supposed to be the string 'rtp' or 'rtcp'. And i'd rather await a decision on https://github.com/w3c/webrtc-pc/issues/1210

**Comment by KaptenJansson** [comment]
LGTM

**Comment by fippo** [comment]
and its called usernameFragment now. But this needs a rebase anyway...

**Comment by KaptenJansson** [comment]
Ready for a rebase?

**Review by KaptenJansson — APPROVED** [review]

**Pull request merged**
