### PR TITLE
all: remove legacy code

### LINKED ISSUE #881: remove some cruft?
pondering if there are some things that should go away together with #880:
* [x] shimming promises in Chrome (<52)
* [x] shimming srcObject in (Chrome version unknown, Firefox since 42)
* [x] shimming iceTransportPolicy in Chrome (51?) for webkitRTCPeerConnection
* [x] ontrack in Firefox (FF46)
* [x] mozRTCPeerConnection stuff with super old url -> urls conversion (version???)
* [x] maplike getstats shim in Firefox (48?)
* [x] ~conversion into RTCSessionDescription, RTCIceCandidate in SRD + addIceCandidate (Firefox 53, too young)~
* [x] old Chrome getUserMedia stuff
* [x] old Firefox getUserMedia stuff

@jan-ivar thoughts?

### PR DESCRIPTION
**Pull request by fippo**
fixes #881

### CODE REVIEW

**Comment by fippo** [comment]
@guidou @KaptenJansson do you recall when navigator.mediaDevices.addEventListener was added in Chrome? Older than Chrome 55 so I'd like to remove this :-)
```
  // Dummy devicechange event methods.
  // TODO(KaptenJansson) remove once implemented in Chrome stable.
```
and while I have your attention... since when can one just pass `{type: 'offer', sdp: '...'}) to setRemoteDescription et al? Works in Chrome 55 as well so...

**Review by guidou — APPROVED** [review]
chrome bits lgtm

**Comment by guidou** [comment]
In Chrome, devicechange shipped in M57

**Comment by fippo** [comment]
and navigator.mediaDevices.getUserMedia shipped in M53 along with navigator.mediaDevices.addEventListener so this seems safe to remove.

Not shimming this provides a nice path to breaking things assuming people use "supports peerconnection and supports navigator.mediaDevices.getUserMedia" as check for WebRTC.

Thank you Guido!

**Review by dagingaa — APPROVED** [review]

**Pull request merged**
