### PR TITLE
Add eslint-config-google and fix eslint errors

### PR DESCRIPTION
**Pull request by KaptenJansson**
**Description**
Use eslint-config-google but disable jsdoc and es6 rules. Tests are exempted and es6 rules are explicit enabled since we use es6 there.

**Purpose**
Adhere to the google style guide.

Note: This is not rebased with the latest changes yet, will do once it's ready before submitting this.

### CODE REVIEW

**Comment by fippo** [comment]
instead of using eslint to fix var -> let i'd rather use https://github.com/cpojer/js-codemod#no-vars in test/

**Comment by KaptenJansson** [comment]
What's the benefit of codemod over eslint? Smarter logic like being context aware?

**Comment by fippo** [comment]
it uses const for things which (in its opinion) are not modified -- like the module requires. And its fairly good with that

**Comment by KaptenJansson** [comment]
Closing for now.

**Pull request closed without merging**
