### PR TITLE
Remove trace function

### PR DESCRIPTION
**Pull request by KaptenJansson**
This mirrors what's done in https://github.com/webrtc/samples/pull/650.

@fippo @samdutton PTAL

### CODE REVIEW

**Comment by samdutton** [comment]
LGTM.

Can't remember if we had discussion about this, but should we find a way for the samples to use adapter.js from the adapter repo — maybe even just by linking to https://raw.githubusercontent.com/webrtc/adapter/master/adapter.js rather than https://webrtc.github.io/samples/src/js/adapter.js?

Feels wrong to maintain two copies.

**Comment by KaptenJansson** [comment]
We do merge the adapter.js version to [gh-pages](https://github.com/webrtc/adapter/tree/gh-pages) (for MS demos) hence it's available to use with a src tag if we want, can either pin it to a specific version or use the symlinked adapter-latest.js pointing to the latest version.

**Comment by fippo** [comment]
i wonder if we should put this on hold until we do a major version bump because of ORTC anyway.

trace isn't exported but I wonder if anyone is using it from the 'raw js' version

**Comment by KaptenJansson** [comment]
closing this as this will be removed as part of the 2.0 refactor in #164

**Pull request closed without merging**
