### PR TITLE
Shim autoGainControl and noiseSuppression

### PR DESCRIPTION
**Pull request by jan-ivar**
**Description**
Shim autoGainControl and noiseSuppression in Chrome and Firefox.

**Purpose**
Match up with spec.

### CODE REVIEW

**Comment by jan-ivar** [comment]
cc @fippo

**Comment by fippo** [comment]
@guidou you probably know more about where chrome expects constraints than I do, can you please take a look?

LGTM but can we have a separate test (two? three?) instead of piggybacking on an existing one? Makes it much easier to review too ;-)

**Comment by KaptenJansson** [comment]
LGTM and I agree that it would be great if it's a separate test.

**Comment by KaptenJansson** [comment]
@guidou could you also take a look?

**Comment by jan-ivar** [comment]
Implemented feedback.

**Comment by guidou** [comment]
lgtm

**Comment by jan-ivar** [comment]
Great! If someone could pull the crank once it's merged to mint a new adapter-latest I'd appreciate it. I have a blog entry ready to go. :)

**Comment by jan-ivar** [comment]
@KaptenJansson ping

**Comment by jan-ivar** [comment]
@KaptenJansson Who can merge?

**Comment by KaptenJansson** [comment]
LGTM

**Pull request merged**
