### PR TITLE
mediaDevices.enumerateDevices() polyfill in adapter.js

### PR DESCRIPTION
**Pull request by jan-ivar**
Add a mediaDevices.enumerateDevices polyfill for Chrome using existing MediaStreamTrack.getSources().

### CODE REVIEW

**Comment by fippo** [comment]
@jan-ivar do you think it's possible to shim MST.getSources with this? Would be nice if people who used it would get the functionality and a warning :-)

**Comment by jan-ivar** [comment]
@fippo sorry just saw your comment. I'd rather not shim non-standard APIs because I worry it works against convergence by allowing people to never update. We want to converge on the spec, not on something else.

For instance, my latest patch here actually removes the MST.getSources() shim from Firefox (that never did anything) in favor of the spec one.

**Comment by jan-ivar** [comment]
Don't people normally copy adapter.js anyway? (I would think linking directly to it would be a cross-origin warning in many browsers).

**Comment by jan-ivar** [comment]
@juberti - please let me know if anything else is needed here as well. I'm excited for feedback.

**Comment by alvestrand** [comment]
Guess this too needs a rebase and a test....

**Pull request closed without merging**
