### PR TITLE
edge: fix two issues

### PR DESCRIPTION
**Pull request by fippo**
see individual commits. tl;dr: the first commit is from the "how did this ever work?" category. The second fixes a regression I introduced when removing the typ endOfCandidates hack

### CODE REVIEW

**Comment by fippo** [comment]
still getting a test failure for the basic test with promises (but callbacks are ok) so I might need another commit to fix things. Will delete this when its ready to merge :-/

**Comment by fippo** [comment]
the tests with promises failed for some reason. Only in the test environment, not when copying them to a html file. @KaptenJansson do you remember why this copy is necessary?

**Comment by KaptenJansson** [comment]
Test environment being nodejs or browser context? AFAIK a browser requires a HTML context for running javascript unless it's an extension.

**Comment by fippo** [comment]
the basic connection establishment with promises test failed but copying that code to a html page worked. Which I find somewhat confusing.

But it works now after not copying the null candidate.

**Comment by KaptenJansson** [comment]
LGTM

**Comment by tgabi333** [comment]
@fippo what is the current status of communicating with edge? does video work somehow?

**Comment by fippo** [comment]
@tgabi333 in the insider builds where H264 is enabled by default -- in the current release build you need to activate a flag

**Comment by tgabi333** [comment]
Thanks @fippo , i didn't get to work it even if i switch experimental H264 support on to transmit video  :S 

Do you have any sample page?

**Comment by fippo** [comment]
@tgabi333 https://simplewebrtc.com/video.html works fine here (latest insider build)

**Pull request merged**
