### PR TITLE
Add autoplay to video tags for all tests

### PR DESCRIPTION
**Pull request by KaptenJansson**
Firefox does not update video.videoHeight and video.videoWidth until the first frame.

### CODE REVIEW

**Comment by fippo** [comment]
LGTM

Should we change the tests (in particular https://github.com/webrtc/adapter/blob/master/test/test.js#L387-L396) to be potentially-async and maybe listen for the video elements onresize?

**Comment by fippo** [comment]
ah... now i understand why this kind-of worked. We are waiting for the element to appear which happens in loadedmetadata. Which apparently is called for videos which don't have autoplay. Maybe we should listen for onresize instead?

**Comment by fippo** [comment]
cross-referencing -- maybe not playing the elements caused https://bugs.chromium.org/p/webrtc/issues/detail?id=4888 ?

**Comment by KaptenJansson** [comment]
Changed to onresize and it seems to work well. Will do async tests in a separate PR if it fails or goes flaky.

**Pull request merged**
