### PR TITLE
Don't shim createObjectURL on old browsers wo/srcObject to avoid infinite recursion.

### PR DESCRIPTION
**Pull request by jan-ivar**
**Description**
Fix for https://github.com/webrtc/adapter/pull/411#issuecomment-275085135.

**Purpose**
Oops.

### CODE REVIEW

**Comment by alvestrand** [comment]
1) Do you have a test for this?
2) It seems that Firefox blows up on Travis, which is odd since the patch doesn't touch Chrome code, and previous builds passed. Can you investigate? (at least run the test locally)

**Comment by fippo** [comment]
This works locally but it seems that we have _some_ issue in Firefox 52 which is now beta. The last successful builds we had with beta were
https://travis-ci.org/webrtc/adapter/jobs/194167230#L727
https://travis-ci.org/webrtc/adapter/jobs/192888091#L741
both of which were FF51.

**Comment by KaptenJansson** [comment]
Yeah it might be worth to add a test for this.

**Comment by flo-sch** [comment]
Works now on Chrome 49 (same environment as yesterday) :)

At least we don't have errors while setting the streams ;
Remote video player has a defined srcObject element, containing both audio and video MediaStreamTracks, which are all enabled ;
RTCPeerConnection is established without error (both session descriptions and ice candidates) ;

But we don't see or hear each other...
Not sure to understand why?

Could it be related to the network, even if ICECandidate are successfully set? (Not using any STUN or TURN server at the moment)

**Comment by alvestrand** [comment]
If possible, can you see what happens if you use a 2.x version of adapter.js?
If that works, and adapter-latest doesn't, it's an adapter bug.

**Comment by flo-sch** [comment]
Hum, yep, same result with adapter@2.1, so it's not related to adapter.js. Sorry about that! I will investigate on the network issues.

**Comment by jan-ivar** [comment]
@alvestrand [#411](https://github.com/webrtc/adapter/pull/411/files#diff-c1129c8b045390789fa8ff62f2c6b4a9R445) added a test for this. It seems to be the one failing in fact. Odd. We don't test old versions of Chrome AFAIK? Unfortunately, I've not been able to run adapter's npm tests locally for over a year, so I've had to test manually with browserify, or by committing and looking at Travis. There's a chance it's provoking a real intermittent we're chasing. Is there a way to re-trigger Travis?

**Comment by alvestrand** [comment]
when you view the run on travis-ci, there's a "restart" button in the upper righthand corner if you have the right to restart; I think it may need to have you in some list of contributors or owners to the repo.
@KaptenJansson  may know more.

**Comment by fippo** [comment]
that button newer worked for me so might require permissions neither @jan-ivar nor me have

**Comment by jan-ivar** [comment]
OK green now, with no change. Looks like an intermittent. :-(

**Comment by fippo** [comment]
@KaptenJansson can you squash before merging? :-)

**Comment by jan-ivar** [comment]
I suspect the 52 intermittent is [bug 1335494](https://bugzil.la/1335494) or [bug 1317126](https://bugzil.la/1317126).

**Comment by KaptenJansson** [comment]
LGTM

**Comment by flo-sch** [comment]
Great :)

Any possible tag for this one ? As it solves a compatibility break, I'd love to update the npm package as a stable release (`3.1.1` maybe?) instead of the commit hash.

**Comment by KaptenJansson** [comment]
@flo-sch 3.1.1 is now published to npm.

**Comment by flo-sch** [comment]
You're the best :)
Thanks a lot!

**Comment by fippo** [comment]
@KaptenJansson https://www.npmjs.com/package/webrtc-adapter still shows 3.1.0

**Comment by flo-sch** [comment]
`npm info webrtc-adapter` makes reference to `3.1.1`, so it's working.

But maybe the NPM page doesn't automatically listen on new releases ? (webhook GitHub ?)

**Comment by fippo** [comment]
it should... but as long as its actually published we're good. Thanks!

**Pull request merged**
