### PR TITLE
Chrome: fix addTrack, removeTrack

### PR DESCRIPTION
**Pull request by Krivega**
**Description**
chrome_shim.js:490 Uncaught TypeError: Cannot read property 'shimAddTrackRemoveTrackWithNative' of undefined

**Purpose**
Fix it

### CODE REVIEW

**Comment by dagingaa** [comment]
Pushed the wrong button :(

**Review by dagingaa — APPROVED** [review]
Thank you for this! `this` here is confusing, but wasn't caught by us since webpack does some magic object-tricks with export currently.

**Comment by fippo** [comment]
out of curiosity, where/how did this happen? Surprised this wasn't caught earlier.

regression in 7.0.0, I don't think its important enough to backport from 7.1.0 but we could for the sake of Dag-Inge training :-)

**Comment by Krivega** [comment]
@fippo just rebuilt my project (CRA) and checked on the latest version of chrome (71.0.3578.80). And indeed, there was no such problem before; apparently, the condition `if (window.RTCPeerConnection.prototype.addTrack` had not passed in chrome before.

**Pull request merged**
