### PR TITLE
feat: add support for react-native

### PR DESCRIPTION
**Pull request by anion155**
**Description**
Handle react-native environment, without any shims.

**Purpose**
https://github.com/webrtcHacks/adapter/issues/1129

### CODE REVIEW

**Comment by saghul** [comment]
Why is this necessary? It already does nothing on RN. Are you running into any problem?

**Comment by anion155** [comment]
Yep. It throws in react native, 'cause there is no `navigator.userAgent`. So any module that using `webrtc-adapter` internally is practically unusable without patching.

**Comment by saghul** [comment]
Gotcha. @fippo I guess adapter shouldn't do anything if `navigator.userAgent` is not a thing.

**Comment by fippo** [comment]
#1132 seems a bit more minimal for that and not specific to RN

**Comment by fippo** [comment]
Can you please give the new version 8.2.3 a try?

**Pull request closed without merging**
