### PR TITLE
test: add electron testing

### PR DESCRIPTION
**Pull request by fippo**
tests in electron on travis

### CODE REVIEW

**Comment by fippo** [comment]
pity, that didn't work out of the box. Will update setup.sh in travis-multirunner to do the download and then rebase

**Comment by KaptenJansson** [comment]
Really cool, hopefully it just works after that.

**Comment by fippo** [comment]
\o/ -- needs rebase on top of #754 but it works

**Review by KaptenJansson — APPROVED** [review]
Really cool and it's quite straight forward to add a new browser thanks to your design of the karma setup we have.

**Pull request merged**
